// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://eltlmnsuuycobfarcwnx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdGxtbnN1dXljb2JmYXJjd254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MDYwMTEsImV4cCI6MjA0Nzk4MjAxMX0.WjIzleo1W8XAWySCL3DImPS-GB1gJN_r24PicREFcgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);